name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "composer.json"
      - "ecs.php"
      - "extension-ecs.php"
      - "rector.php"
      - "extension-rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code_l12:
    name: "Code check - Laravel 12"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a175c9b9239a356b40362a649c790ced8efc9e42
    with:
      composerRequireDev: "laravel/framework:^v12"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  code_l13:
    name: "Code check - Laravel 13"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a175c9b9239a356b40362a649c790ced8efc9e42
    with:
      composerRequireDev: "laravel/framework:^v13"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.3", "8.4", "8.5" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@a175c9b9239a356b40362a649c790ced8efc9e42
    with:
      gistOnPhpVersion: "8.3"
      gistID: 9430d7a714e7868dbeb2d1a8fc3da817
      phpVersion: "${{ matrix.phpVersion }}"
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
