name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "composer.json"
      - "ecs.php"
      - "extension-ecs.php"
      - "rector.php"
      - "extension-rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_l9:
    name: "Code check - Laravel 9"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a4ea3cf7a947ef8baef8359f184d2bc1feefd8bf
    with:
      composerRequireDev: "orchestra/testbench:^v7"
    secrets: inherit

  code_l10:
    name: "Code check - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a4ea3cf7a947ef8baef8359f184d2bc1feefd8bf
    with:
      composerRequireDev: "orchestra/testbench:^v8"
    secrets: inherit

  code_l11:
    name: "Code check - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@a4ea3cf7a947ef8baef8359f184d2bc1feefd8bf
    with:
      composerRequireDev: "orchestra/testbench:^v9"
      composerRequire: "php:'>=8.2'"
    secrets: inherit
