name: "Code check"

on:
  push:
    branches:
      - "main"

  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "composer.json"
      - "ecs.php"
      - "extension-ecs.php"
      - "rector.php"
      - "extension-rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"

concurrency:
  group: conventions-check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code_l10:
    name: "Code check - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v8"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  code_l11:
    name: "Code check - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v9"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit
